apiVersion: v1
kind: Pod
metadata:
  name: ebpf_exporter
spec:
  terminationGracePeriodSeconds: 30
  containers:
    - name: ebpf_exporter
      image: digitalocean/ebpf_exporter:latest
      args:
        - --prog-stats-mode=sample
        - --prog-stats-sample-duration=5s
        - --prog-stats-sample-interval=30s
        - --map-count-entries
        - --log-level=debug
      securityContext:
        privileged: true
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 1024Mi
          cpu: 1000m
      env:
        - name: GOMAXPROCS
          value: "1"
